site_name: My Docs
site_url: https://fduzs.github.io/wiki
theme:
  name: material

markdown_extensions:
  # Content tabs
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  # Images
  - attr_list
  - md_in_html

plugins:
  # Lightbox
  - glightbox
