site_name: Wiki
site_url: https://fduzs.github.io/wiki

repo_name: FDUZS/wiki
repo_url: https://github.com/FDUZS/wiki

theme:
  name: material
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
    tag:
      html: fontawesome/brands/html5
      js: fontawesome/brands/js
      css: fontawesome/brands/css3
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - toc.follow
    # - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - navigation.footer
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

plugins:
  # Lightbox
  - glightbox:
  - search:
      lang:
        - en
  # - social
  - tags:

extra:
  generator: true
  tags:
    HTML5: html
    JavaScript: js
    CSS: css
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/FDUZS
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/shuaizheng_org

markdown_extensions:
  # Content tabs
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

  # Images
  - attr_list
  - md_in_html

  # Formatting
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  # Admonitions
  - admonition
  - pymdownx.details
  # - pymdownx.superfences

  # Data tables
  - tables

  # Footnotes
  - footnotes

  # Icons, Emojis
  # - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: index.md
  - GFW:
      - gfw/index.md
      - 廉价机场众生相: gfw/cheap-proxy-providers.md
      - 机场订阅聚合与转换: gfw/proxy-bundle-and-conversion.md
      - 常用代理设置: gfw/proxy-configurations.md
      - 用 IPv6 来拯救你的校园网: gfw/ssr-ipv6-proxifier.md
  - AI:
      - ai/index.md
  - Python:
      - python/index.md
      - Microsoft Visual C++ 14.0 or greater is required: python/python-vc-14-error.md
  - Tool:
      - tool/index.md
      - SSH 设置: tool/ssh.md
      - Zotero 设置: tool/zotero-setup.md
  - VPS:
      - vps/index.md
      - Scaleway Stardust IPv6 VPS: vps/scaleway-stardust-ipv6-vps.md
